apiVersion: v1
kind: Secret
metadata:
  name: {{ include "reckon.fullname" . }}-secrets
  labels:
    {{- include "reckon.labels" . | nindent 4 }}
type: Opaque
stringData:
  WAREHOUSE_TYPE: {{ .Values.warehouse.type | quote }}
  POSTGRES_HOST: {{ .Values.warehouse.host | quote }}
  POSTGRES_PORT: {{ .Values.warehouse.port | quote }}
  POSTGRES_DB: {{ .Values.warehouse.db | quote }}
  POSTGRES_USER: {{ .Values.warehouse.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.warehouse.password | quote }}
  REDSHIFT_HOST: {{ .Values.warehouse.host | quote }}
  REDSHIFT_PORT: {{ .Values.warehouse.port | quote }}
  REDSHIFT_DB: {{ .Values.warehouse.db | quote }}
  REDSHIFT_USER: {{ .Values.warehouse.user | quote }}
  REDSHIFT_PASSWORD: {{ .Values.warehouse.password | quote }}
  DATA_LAKE_TYPE: {{ .Values.lake.type | quote }}
  S3_BUCKET: {{ .Values.lake.bucket | quote }}
  AWS_REGION: {{ .Values.lake.region | quote }}
