// Load seed jobs into the reckon.jobs collection on first start.
// The JSON was generated by scripts/generate_job_seed.py using the same
// deterministic Aria call seed, so related_call_id values match.

const fs = require("fs");
const data = fs.readFileSync("/docker-entrypoint-initdb.d/seed_jobs.json", "utf8");
const jobs = JSON.parse(data);

db = db.getSiblingDB("reckon");
db.jobs.drop();
db.jobs.insertMany(jobs);
print("Seeded " + jobs.length + " jobs into reckon.jobs");
